import type {
  DividendPoolSeed,
  GrowthPoolSeed,
  OverlapPoolSeed,
  WatchlistPoolId,
  WatchlistPoolMeta,
} from './types';

export const WATCHLIST_DATA_DATE = '2026-08-26';

export const DIVIDEND_POOL_SEED: readonly DividendPoolSeed[] = [
  {
    symbol: '601398',
    name: '工商银行',
    industry: '银行',
    dividendPerShare2023: 0.3064,
    dividendPerShare2024: 0.308,
    dividendPerShare2025: 0.3103,
    referenceYieldPercent: 3.92,
    referenceLotCost: 792,
    stability: 'A',
    thesis: '客户基础和资产规模稳；关注净息差、地产及地方债风险。',
  },
  {
    symbol: '601288',
    name: '农业银行',
    industry: '银行',
    dividendPerShare2023: 0.2309,
    dividendPerShare2024: 0.2419,
    dividendPerShare2025: 0.2495,
    referenceYieldPercent: 3.64,
    referenceLotCost: 686,
    stability: 'A',
    thesis: '县域金融优势突出；关注净息差和信用成本。',
  },
  {
    symbol: '600036',
    name: '招商银行',
    industry: '银行',
    dividendPerShare2023: 1.972,
    dividendPerShare2024: 2,
    dividendPerShare2025: 2.016,
    referenceYieldPercent: 5.07,
    referenceLotCost: 3980,
    stability: 'A+',
    thesis: '零售与财富管理能力较强；关注零售资产质量和估值波动。',
  },
  {
    symbol: '601825',
    name: '沪农商行',
    industry: '银行',
    dividendPerShare2023: 0.379,
    dividendPerShare2024: 0.432,
    dividendPerShare2025: 0.435,
    referenceYieldPercent: 4.94,
    referenceLotCost: 881,
    stability: 'A+',
    thesis: '区域存款基础较好；关注区域集中和中小企业信用风险。',
  },
  {
    symbol: '600919',
    name: '江苏银行',
    industry: '银行',
    dividendPerShare2023: 0.47,
    dividendPerShare2024: 0.5206,
    dividendPerShare2025: 0.5641,
    referenceYieldPercent: 4.69,
    referenceLotCost: 1204,
    stability: 'A+',
    thesis: '股息持续提升；关注区域信用周期与快速扩张风险。',
  },
  {
    symbol: '600941',
    name: '中国移动',
    industry: '通信',
    dividendPerShare2023: 4.4096,
    dividendPerShare2024: 4.6705,
    dividendPerShare2025: 4.7037,
    referenceYieldPercent: 4.78,
    referenceLotCost: 9845,
    stability: 'A+',
    thesis: '现金流和派息政策较强；关注资本开支及政策定价。',
  },
  {
    symbol: '601728',
    name: '中国电信',
    industry: '通信',
    dividendPerShare2023: 0.2332,
    dividendPerShare2024: 0.2598,
    dividendPerShare2025: 0.272,
    referenceYieldPercent: 4.24,
    referenceLotCost: 642,
    stability: 'A',
    thesis: '派息率和股息持续提升；关注资本开支与业务增速。',
  },
  {
    symbol: '600900',
    name: '长江电力',
    industry: '水电',
    dividendPerShare2023: 0.82,
    dividendPerShare2024: 0.943,
    dividendPerShare2025: 1,
    referenceYieldPercent: 3.54,
    referenceLotCost: 2824,
    stability: 'A',
    thesis: '水电现金流和长期派息规划较明确；关注来水、利率和估值。',
  },
  {
    symbol: '600886',
    name: '国投电力',
    industry: '电力',
    dividendPerShare2023: 0.4948,
    dividendPerShare2024: 0.4565,
    dividendPerShare2025: 0.5081,
    referenceYieldPercent: 3.62,
    referenceLotCost: 1405,
    stability: 'B+',
    thesis: '水火电组合，2025年股息恢复；关注来水、煤价和资本开支。',
  },
  {
    symbol: '600674',
    name: '川投能源',
    industry: '水电',
    dividendPerShare2023: 0.4,
    dividendPerShare2024: 0.4,
    dividendPerShare2025: 0.5,
    referenceYieldPercent: 3.19,
    referenceLotCost: 1569,
    stability: 'A',
    thesis: '受益于雅砻江水电；关注资产集中和来水风险。',
  },
  {
    symbol: '600025',
    name: '华能水电',
    industry: '水电',
    dividendPerShare2023: 0.18,
    dividendPerShare2024: 0.2,
    dividendPerShare2025: 0.205,
    referenceYieldPercent: 2.1,
    referenceLotCost: 976,
    stability: 'A-',
    thesis: '股息缓慢上升，但当前收益率偏低；关注来水和建设期风险。',
  },
  {
    symbol: '600461',
    name: '洪城环境',
    industry: '公用事业',
    dividendPerShare2023: 0.4407,
    dividendPerShare2024: 0.464,
    dividendPerShare2025: 0.467,
    referenceYieldPercent: 5.24,
    referenceLotCost: 891,
    stability: 'A+',
    thesis: '供水、污水业务现金流相对稳定；关注应收款和地方财政。',
  },
  {
    symbol: '600350',
    name: '山东高速',
    industry: '高速公路',
    dividendPerShare2023: 0.42,
    dividendPerShare2024: 0.42,
    dividendPerShare2025: 0.42,
    referenceYieldPercent: 3.87,
    referenceLotCost: 1084,
    stability: 'A',
    thesis: '连续三年每股0.42元；关注交通量、并购与高派息压力。',
  },
  {
    symbol: '600377',
    name: '宁沪高速',
    industry: '高速公路',
    dividendPerShare2023: 0.47,
    dividendPerShare2024: 0.49,
    dividendPerShare2025: 0.49,
    referenceYieldPercent: 3.94,
    referenceLotCost: 1244,
    stability: 'A',
    thesis: '成熟路产、股息稳定；关注特许经营期限和扩建支出。',
  },
  {
    symbol: '000429',
    name: '粤高速A',
    industry: '高速公路',
    dividendPerShare2023: 0.547,
    dividendPerShare2024: 0.523,
    dividendPerShare2025: 0.604,
    referenceYieldPercent: 4.49,
    referenceLotCost: 1344,
    stability: 'B+',
    thesis: '2025年股息回升；关注交通量与单一区域风险。',
  },
  {
    symbol: '000333',
    name: '美的集团',
    industry: '家电',
    dividendPerShare2023: 3,
    dividendPerShare2024: 3.5,
    dividendPerShare2025: 4.3,
    referenceYieldPercent: 4.98,
    referenceLotCost: 8639,
    stability: 'A+',
    thesis: '现金流、分红与回购兼具；关注需求、汇率和海外贸易。',
  },
  {
    symbol: '600690',
    name: '海尔智家',
    industry: '家电',
    dividendPerShare2023: 0.8013,
    dividendPerShare2024: 0.965,
    dividendPerShare2025: 1.1607,
    referenceYieldPercent: 5.49,
    referenceLotCost: 2115,
    stability: 'A+',
    thesis: '盈利与股息同步提升；关注海外需求、汇率和整合风险。',
  },
  {
    symbol: '600660',
    name: '福耀玻璃',
    industry: '汽车零部件',
    dividendPerShare2023: 1.3,
    dividendPerShare2024: 1.8,
    dividendPerShare2025: 2.1,
    referenceYieldPercent: 3.67,
    referenceLotCost: 5720,
    stability: 'A',
    thesis: '高附加值玻璃带动盈利和派息；关注汽车周期及海外经营。',
  },
  {
    symbol: '000651',
    name: '格力电器',
    industry: '家电',
    dividendPerShare2023: 2.38,
    dividendPerShare2024: 3,
    dividendPerShare2025: 3,
    referenceYieldPercent: 7.22,
    referenceLotCost: 4158,
    stability: 'A+',
    thesis: '高股息、现金创造力较强；关注空调业务集中、渠道及治理。',
  },
  {
    symbol: '000423',
    name: '东阿阿胶',
    industry: '中药',
    dividendPerShare2023: 1.7842,
    dividendPerShare2024: 2.4197,
    dividendPerShare2025: 2.7056,
    referenceYieldPercent: 5.54,
    referenceLotCost: 4880,
    stability: 'A+',
    thesis: '品牌恢复带动利润和股息提升；关注产品集中、库存和估值。',
  },
];

export const GROWTH_POOL_SEED: readonly GrowthPoolSeed[] = [
  {
    symbol: '000333',
    name: '美的集团',
    industry: '白色家电',
    revenueCagrPercent: 10.8,
    profitCagrPercent: 14.2,
    roe2025Percent: 19.7,
    drivers: '全球化、工业技术、机器人与能源管理。',
    risks: '海外需求、汇率及并购整合。',
  },
  {
    symbol: '600690',
    name: '海尔智家',
    industry: '白色家电',
    revenueCagrPercent: 5,
    profitCagrPercent: 8.5,
    roe2025Percent: 17,
    drivers: '海外本地化、高端品牌和数字化降费。',
    risks: '海外需求、汇率及原材料。',
  },
  {
    symbol: '002475',
    name: '立讯精密',
    industry: '消费电子',
    revenueCagrPercent: 19.7,
    profitCagrPercent: 23.1,
    roe2025Percent: 21.1,
    drivers: '消费电子份额提升，汽车与AI硬件连接业务扩张。',
    risks: '大客户集中、资本开支和低毛利。',
  },
  {
    symbol: '600660',
    name: '福耀玻璃',
    industry: '汽车零部件',
    revenueCagrPercent: 17.5,
    profitCagrPercent: 28.6,
    roe2025Percent: 25.6,
    drivers: '智能天幕、HUD玻璃和海外产能释放。',
    risks: '汽车销量、海外贸易和扩产风险。',
  },
  {
    symbol: '600276',
    name: '恒瑞医药',
    industry: '创新药',
    revenueCagrPercent: 17.7,
    profitCagrPercent: 33.9,
    roe2025Percent: 14.3,
    drivers: '创新药管线、国际授权和研发兑现。',
    risks: '研发失败、集采和高估值。',
  },
  {
    symbol: '000423',
    name: '东阿阿胶',
    industry: '中药',
    revenueCagrPercent: 19.2,
    profitCagrPercent: 22.9,
    roe2025Percent: 16.7,
    drivers: '品牌修复、健康消费和渠道提效。',
    risks: '产品集中、库存和提价持续性。',
  },
  {
    symbol: '688041',
    name: '海光信息',
    industry: '半导体',
    revenueCagrPercent: 54.6,
    profitCagrPercent: 41.9,
    roe2025Percent: 11.9,
    drivers: '国产CPU/DCU与AI算力需求。',
    risks: '高估值、技术迭代和客户集中。',
  },
  {
    symbol: '300308',
    name: '中际旭创',
    industry: '通信设备',
    revenueCagrPercent: 88.9,
    profitCagrPercent: 122.9,
    roe2025Percent: 43.8,
    drivers: 'AI数据中心高速光模块升级。',
    risks: '客户集中、价格下降和行业周期。',
  },
  {
    symbol: '002920',
    name: '德赛西威',
    industry: '汽车电子',
    revenueCagrPercent: 21.9,
    profitCagrPercent: 25.9,
    roe2025Percent: 21.7,
    drivers: '智能座舱、域控制器与辅助驾驶渗透。',
    risks: '车企降价、客户集中和研发投入。',
  },
  {
    symbol: '002028',
    name: '思源电气',
    industry: '电网设备',
    revenueCagrPercent: 31.5,
    profitCagrPercent: 42.1,
    roe2025Percent: 22.6,
    drivers: '国内电网投资和海外输配电扩张。',
    risks: '项目交付、原材料及海外政策。',
  },
  {
    symbol: '300274',
    name: '阳光电源',
    industry: '新能源设备',
    revenueCagrPercent: 11.1,
    profitCagrPercent: 19.4,
    roe2025Percent: 31.3,
    drivers: '储能系统、逆变器和全球渠道。',
    risks: '行业价格战、海外政策和库存。',
  },
  {
    symbol: '300866',
    name: '安克创新',
    industry: '消费电子',
    revenueCagrPercent: 32,
    profitCagrPercent: 25.5,
    roe2025Percent: 26.1,
    drivers: '全球品牌、多品类和线上线下渠道扩张。',
    risks: '平台依赖、汇率和消费需求。',
  },
  {
    symbol: '605499',
    name: '东鹏饮料',
    industry: '饮料',
    revenueCagrPercent: 36.1,
    profitCagrPercent: 47.1,
    roe2025Percent: 51.6,
    drivers: '渠道下沉、全国化和第二品类。',
    risks: '单品集中、竞争和估值偏高。',
  },
  {
    symbol: '603129',
    name: '春风动力',
    industry: '摩托车',
    revenueCagrPercent: 27.7,
    profitCagrPercent: 29,
    roe2025Percent: 24.5,
    drivers: '大排量产品、出口和产品结构升级。',
    risks: '海外需求、贸易壁垒和汇率。',
  },
  {
    symbol: '600312',
    name: '平高电气',
    industry: '电网设备',
    revenueCagrPercent: 6.3,
    profitCagrPercent: 17.2,
    roe2025Percent: 10.3,
    drivers: '特高压建设和电网更新周期。',
    risks: '订单节奏、原材料和项目周期。',
  },
  {
    symbol: '000999',
    name: '华润三九',
    industry: '中药',
    revenueCagrPercent: 13,
    profitCagrPercent: 9.5,
    roe2025Percent: 16.1,
    drivers: 'OTC品牌、处方药和并购协同。',
    risks: '并购整合、集采和商誉。',
  },
  {
    symbol: '002050',
    name: '三花智控',
    industry: '家电零部件',
    revenueCagrPercent: 12.4,
    profitCagrPercent: 17.9,
    roe2025Percent: 15.8,
    drivers: '热管理从家电向新能源汽车延伸。',
    risks: '车企降价、客户集中和估值。',
  },
  {
    symbol: '600885',
    name: '宏发股份',
    industry: '电网设备',
    revenueCagrPercent: 15.3,
    profitCagrPercent: 12.3,
    roe2025Percent: 17.2,
    drivers: '继电器在新能源、汽车和电力系统扩张。',
    risks: '制造周期、原材料和海外需求。',
  },
  {
    symbol: '600066',
    name: '宇通客车',
    industry: '商用车',
    revenueCagrPercent: 23.8,
    profitCagrPercent: 74.8,
    roe2025Percent: 38,
    drivers: '新能源客车更新、出口和盈利结构改善。',
    risks: '高基数、订单波动和海外政策。',
  },
  {
    symbol: '601138',
    name: '工业富联',
    industry: '消费电子',
    revenueCagrPercent: 37.7,
    profitCagrPercent: 29.5,
    roe2025Percent: 21.6,
    drivers: 'AI服务器与高速网络设备放量。',
    risks: '大客户集中、低毛利和AI投资周期。',
  },
];

export const OVERLAP_POOL_SEED: readonly OverlapPoolSeed[] = [
  {
    symbol: '000333',
    name: '美的集团',
    positioning: '高质量股息成长',
    notes: '一手成本较高，不适合一万元账户重仓。',
  },
  {
    symbol: '600690',
    name: '海尔智家',
    positioning: '消费分红核心',
    notes: '在四只交集股中，一手成本相对更适合小资金。',
  },
  {
    symbol: '600660',
    name: '福耀玻璃',
    positioning: '制造成长+股息增长',
    notes: '汽车周期和海外经营可能带来较大波动。',
  },
  {
    symbol: '000423',
    name: '东阿阿胶',
    positioning: '品牌修复+股息增长',
    notes: '产品集中、渠道库存和估值需要持续跟踪。',
  },
];

const POOL_HIGHLIGHTS: Record<WatchlistPoolId, readonly string[]> = {
  dividend: [
    '银行股只适合从中选择 1—2 只，不能因为名单中数量多就全部配置。',
    '高速公路建议只选 1 只，三只公司的风险来源较接近。',
    '华能水电分红稳定但股息率偏低，适合等待估值提供更高安全边际。',
    '格力电器股息率最高，但业务集中度和治理风险也高于公用事业、通信类公司。',
  ],
  growth: [
    '海光信息、中际旭创、工业富联具有 AI 算力逻辑，但估值和业绩波动明显高于消费、公用事业类公司。',
    '宇通客车利润增速很高，部分来自盈利修复和低基数，不能简单外推未来三年。',
    '东鹏饮料 ROE 和增长率较高，但单品依赖和估值风险需要重点控制。',
    '海尔智家增长率不高，但经营稳定性、现金流和分红更适合稳健风格。',
  ],
  overlap: [
    '同时满足分红连续与 2023—2025 收入、利润逐年增长。',
    '进入股票池不等于可以买入，仍需结合估值、股息率和价格趋势确定买点。',
  ],
};

const POOL_DESCRIPTIONS: Record<WatchlistPoolId, string> = {
  dividend:
    '连续分红、参考股息率与稳定性评级。财务快照来自 2026-08-26 研究文档，现价与股息率由东方财富行情实时刷新。',
  growth:
    '2023—2025 营收与归母净利润均逐年增加。CAGR 与 ROE 为文档快照，现价由行情 API 刷新。',
  overlap: '稳定分红池与稳定成长池的交集，兼顾股息连续性与业绩成长。',
};

export function listWatchlistPoolMeta(): WatchlistPoolMeta[] {
  return [
    {
      id: 'dividend',
      title: '稳定分红池',
      description: POOL_DESCRIPTIONS.dividend,
      dataDate: WATCHLIST_DATA_DATE,
      itemCount: DIVIDEND_POOL_SEED.length,
    },
    {
      id: 'growth',
      title: '稳定成长池',
      description: POOL_DESCRIPTIONS.growth,
      dataDate: WATCHLIST_DATA_DATE,
      itemCount: GROWTH_POOL_SEED.length,
    },
    {
      id: 'overlap',
      title: '分红 × 成长交集',
      description: POOL_DESCRIPTIONS.overlap,
      dataDate: WATCHLIST_DATA_DATE,
      itemCount: OVERLAP_POOL_SEED.length,
    },
  ];
}

export function getWatchlistHighlights(poolId: WatchlistPoolId): readonly string[] {
  return POOL_HIGHLIGHTS[poolId];
}

export function findDividendSeed(symbol: string): DividendPoolSeed | undefined {
  return DIVIDEND_POOL_SEED.find((item) => item.symbol === symbol);
}

export function findGrowthSeed(symbol: string): GrowthPoolSeed | undefined {
  return GROWTH_POOL_SEED.find((item) => item.symbol === symbol);
}
