export const ipcChannels = {
  health: 'desktop:health',
  assetStats: 'desktop:assets:stats',
  importImage: 'desktop:assets:import-image',
  workspaceSnapshot: 'desktop:workspace:snapshot',
  listPlans: 'desktop:plans:list',
  createPlan: 'desktop:plans:create',
  setPlanStatus: 'desktop:plans:set-status',
  listAlerts: 'desktop:alerts:list',
  createAlert: 'desktop:alerts:create',
  setAlertStatus: 'desktop:alerts:set-status',
  evaluateAlertPrice: 'desktop:alerts:evaluate-price',
  listReviews: 'desktop:reviews:list',
  createReview: 'desktop:reviews:create',
  generateReviewAiDraft: 'desktop:reviews:generate-ai-draft',
  getLlmStatus: 'desktop:settings:llm-status',
  saveLlmApiKey: 'desktop:settings:save-llm-api-key',
  testLlmConnection: 'desktop:settings:test-llm-connection',
  updateState: 'desktop:update:state',
  getUpdateState: 'desktop:update:get-state',
  checkForUpdates: 'desktop:update:check',
  downloadUpdate: 'desktop:update:download',
  installUpdate: 'desktop:update:install',
  openUpdateRelease: 'desktop:update:open-release',
} as const;
